### ISSUE TITLE
Question: Where is the installer or binaries? And is Haveno ready to be used?

### ISSUE THREAD

**Issue by godfuture** [haveno-dex/haveno#1070]
Hello guys,
I struggled to get this ship startin. In release section I can only find a zip with source code, but no binaries. How do I get the mentioned installer or binaries to start installation?

And as LocalMonero goes down, I urgently need a proper replacement. Is Haveno ready to be used? Or is clear when it will be?

Thanks guys!

**Comment by boldsuck** [comment]
Hi, Haven-dex only develops the code.
THERE ARE NO OFFICIAL HAVENO NETWORK INSTANCES, THERE ARE ONLY THIRD PARTY HAVENO NETWORKS LIKE HAVENO RETO. I have been trading there for 40 days.
@nihilist001 has made very nice HowTo's [haveno-client-f2f](https://blog.nihilism.network/servers/haveno-client-f2f/index.html)
or [haveno-sepa](https://blog.nihilism.network/servers/haveno-sepa/index.html)
Since Haveno is a bisq fork can this also help [getting-started](https://bisq.network/getting-started/l)

**Comment by godfuture** [comment]
I am afraid I don't understand what network means here. Maybe it would help to explain this better also here in github.
Can I trust the reto network? I wonder why I have to install binaries from this network. Is the network baked into the app? Why not using client from here and configuring reto network?

**Comment by boldsuck** [comment]
The haveno-dex devs have decided not to operate a Haveno mainnet due to legal concerns. Haveno-dex only runs on the testnet, more precisely Monero stagenet.
Haveno-reto is a 1:1 fork of Haven-Dex in which the mainnet seednodes, -pricenodes and arbitrator keys are added.

Haveno-reto has to earn the trust in the same way as localmonero did back then. I can only say for myself that I have made some trades without any problems and I trust the Haveno-reto arbs more than any CEX that suddenly blocks the withdrawal of coins. The individual trades are P2P.

Start with small amounts & as always, DYOR:

- [monero.town](https://monero.town/search?q=haveno&type=All&listingType=All&page=1&sort=TopAll)
- [Monero Topia](https://iv.datura.network/watch?v=hWcwin8bDpc&t=1h9m11s)
- The tutorials by @nihilist001 mentioned above. There's a lot more good stuff about privacy & anonymity.
- There is also #haveno IRC//Libera or [Matrix room](https://matrix.to/#/#haveno:monero.social)
- Generally in the Monero community resources and be careful with HavenoMain, this is a SCAM attempt.

**Comment by godfuture** [comment]
Closing ticket as answer was provided.
