### ISSUE TITLE
randomize completed trade info

### ISSUE THREAD

**Issue by XMRfamily** [haveno-dex/haveno#1099]
like, if you trade $100 it shows anything from 95 to 105 

And time wise it's randomized or daily tallied. There is some privacy/security/opsec concerns with having it easily findable. Sure bad actor could find out malicious but we should try to improve the privacy. Patterns could be established to better track traders.

Don't know if this is even possible but should be looked into

**Comment by monerobull** [comment]
This issue has been conceptualized in collaboration between XMRfamily and monerobull 🤝

I'm not sure about the time because trade time already differs from payment time and malicious actors could observe and time initial broadcasts of trade data anyways. Probably too much work for little actual gain to add something like only reporting to arbitrator who caches the data till a specific time.

**Comment by woodser** [comment]
It's been considered if any trade stats should be published at all versus operating with unknown volumes.

Alternatively, maybe the trade dates and amounts could be adjusted, e.g. dates randomized within 24 hours, amounts randomized +/-5%.

**Comment by nihilist001** [comment]
+1, you dont want a threat actor to look up haveno stats and use a specific transaction against you. for plausible deniability's sake.

**Comment by monerobull** [comment]
i really like looking at the haveno volume/price graph but i'd be willing to sacrifice it for the greater good 🥲

**Comment by XMRfamily** [comment]
Trade stats are cool for marketing and advertising, but as platform grows will become more safety risk.

**Comment by monerobull** [comment]
Maybe keep randomized stats for a few months and then re-consider if they should be removed or not?

**Comment by haveno-user** [comment]
I want that data for my own reference, complete and unfuzzed, so I'll just set up a bot to log it.  Somebody else will put it on a web site and put ads around it, or charge money for access to it, like public records aggregators.  You would only be hiding it from yourselves.  By making it slightly harder to get, you are only making it worth more.

**Comment by charcharchar** [comment]
The way stats are pretty bad for privacy. But if all stats were removed then how would people know what payment methods or currencies were used by people in order to know what offers to make to improve chance of success of making a quick trade? Also stats/counts on disputes would be handy to know so people can make their own mind up if they should choose a payment method or not. Good if bugs or trader issue can be identified as the reason for dispute too.

**Comment by woodser** [comment]
Unfortunately I needed to revert https://github.com/haveno-dex/haveno/pull/1119, because it causes clients to re-publish the same trades over and over again, due to not recognizing previously fuzzed trades as their own.

So this issue still needs a solution for this.
