### ISSUE TITLE
Portfolio not showing my open offer

### ISSUE THREAD

**Issue by superhans65** [haveno-dex/haveno#1110]
I have made an offer to buy. It's listed under "BUY" as available. When I go to "Portfolio", there's nothing under any tabs. I tried export to CSV, and that's blank too.

I wonder what will happens if I remove it. Will my XMR be returned or disappear?

v1.0.8 on ubuntu

Edit: the offer has now disappeared. Seemingly by itself. I think the XMR was returned. I hope it was. No trail to follow the money, so a bit tricky to know.  No transactions showing. Nothing in Portfolio/History. But looking at my balance, it looks pretty right.

**Comment by woodser** [comment]
Offers have been knocked offline due to no arbitrators being available to provide a valid signature.

Opened an issue to keep these offers offline and occasionally retry signing and posting: https://github.com/haveno-dex/haveno/issues/1115

> I think the XMR was returned

Yes the XMR becomes available again when an offer is removed.

**Comment by woodser** [comment]
Fixed by https://github.com/haveno-dex/haveno/pull/1132
