### ISSUE TITLE
Can't take offer because arbitrator signature invalid

### ISSUE THREAD

**Issue by balz666** [haveno-dex/haveno#1192]
When I click on "Take Offer", the following appears : 

![image](https://github.com/user-attachments/assets/99ee791f-2e54-4a8f-97bd-9ad779037c50)

I can't create an offer as well. If I try, the following appears : 

![image](https://github.com/user-attachments/assets/fa53c861-9748-49b0-9e79-10a498eafb69)

I did some research and some people on bisq reported the same thing and the advice was to restart the software. Problem is it took me like 5 hours and 10-15 times trying to finally get it (there was no seed nodes, or it would be doing nothing forever, etc.), so I wouldn't want to close it and start from scratch.

Anyone had the same problem and know how to solve this?

**Comment by boldsuck** [comment]
This often happens when there is no connection to the XMR-RPC wallet. It is best to use local monerod.

You can get seed node addresses in the [SimpleX group.](https://haveno-reto.com/) Version 1.0.10 brings some new seed nodes to the client.
Or try the one from Ms. anon3 and anon6 [xmr_mainnet.seednodes](https://github.com/boldsuck/haveno-retodev/blob/master/core/src/main/resources/xmr_mainnet.seednodes)

**Comment by woodser** [comment]
Closing because it's likely related to connectivity issues with a third party network you're using.
