### ISSUE TITLE
custom monero node settings improvements

### ISSUE THREAD

**Issue by charcharchar** [haveno-dex/haveno#1382]
If your custom node is not available haveno will silently use a public tor node. On the next start of haveno, even if your custom node is available haveno will use a tor public node. Suggest to pause and ask to use public node if custom node is not available or try again button. If your custom node is available on next restart to ensure the custom node is used.

This was experienced when running a monero on the localnetwork. haveno and monerod was not running on the same machine.

Also it would be nice to see at the buttom status pane to show exact monero node address that is being connected to and if its a custom personal node or public and if tor or clearnet.

If possible, scan the local subnet for any local monero nodes and ask to use it.

**Comment by boldsuck** [comment]
> This was experienced when running a monero on the localnetwork. haveno and monerod was not running on the same machine.

Strange:
I have one default monerod in `xmrNode=clearnet` and the rest as a list in `xmrNodes=some_onion` With setting: "Use Tor after wallet is syncronised."
If the nodes are not accessible via tor¹, Haveno GUI does not switch to default nodes for me, but in the bottom left of the GUI it says 'in red' Not synced with Monero mainnet.
¹Of course, this happens more often.

**Comment by charcharchar** [comment]
By the way, this is from GUI setting ''network info-use custom monero nodes', not the command line. And launching haveno without arguments. I expect this would be common way to set haveno to use your monero node on the local network.

Separate note - i noticed someone report somewhere that they didnt want to use their localhost monero node on their local machine haveno was running on. Perhaps haveno should ask if localhost node is detected and ASK before using or use remote haveno defaults.

**Comment by boldsuck** [comment]
> By the way, this is from GUI setting ''network info-use custom monero nodes', not the command line.

 `--xmrNodes=` is the same as in the GUI `> Use custom Monero nodes`
`--useTorForXmr=<AFTER_SYNC|OFF|ON>` is the same as in the GUI `> Use Tor for Monero network`

You can also specify all [cmdline options](https://gist.github.com/boldsuck/5fb0d6a58e2a675abfe4d7a266b66da9) in `~/.local/share/Haveno/haveno.properties` or a mainnet e.g.: reto is in `~/.local/share/Haveno-reto/haveno.properties
`

Monero node for RPC wallet can only be configured via cmdline or in haveno.properties.
`--xmrNode=`  URI of custom Monero node to use
`--xmrNodeUsername=`  Username of custom Monero node to use
`--xmrNodePassword=`  Password of custom Monero node to use

> Separate note - i noticed someone report somewhere that they didnt want to use their localhost monero node on their local machine haveno was running on

Using a localhost monero node is recommended because of privacy and reliability. If you use a remote node for the Haveno RPC wallet, the app takes longer to start and you constantly have problems when placing or accepting offers.

`--xmrNode=` should only be configured if you want to connect your wallet to a node in your network instead of localhost.

It is not always useful what others want to configure. Someone somewhere wanted to use Haveno RPC wallet with his local monerod over Tor (.onion address). That means he connects 2 **local** services over a dozen Tor nodes on the internet. ;-)

> Also it would be nice to see at the buttom status pane to show exact monero node address that is being connected to

Yes, it would be nice to see the address of the Haveno RPC wallet node in the GUI.

In the GUI **NETWORK INFO** Monero network, connected peers:
[Haveno Network Info](https://i.postimg.cc/Z583CfBB/Haveno-network-info.png)
maybe something is only displayed for local nodes. For me it always says: Currently there is no data available

_Currently, is been there for over 12 months ;-)_
