### ISSUE TITLE
Create document to guide design of Haveno

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#22]
This issue requests documenting key goals of Haveno (e.g. simplicity) and differences from Bisq (e.g. 2/3 multisig vs 2/2 multisig + refund process) in order to guide user interface design.

**Comment by newsyp** [comment]
I was thinking, why can't haveno just offer both?

**Comment by woodser** [comment]
@newsyp Both what?  2/3 multisig and 2/2 multisig with a refund process?

**Comment by newsyp** [comment]
> @newsyp Both what? 2/3 multisig and 2/2 multisig with a refund process?

Yea like where the user can choose to open a trade with either 2/3 multisig or with 2/2 multisig and refund. If this can implemented, why not give the user the ability to decide which type of trade they wish to engage in? 

Best of both worlds right?

**Comment by woodser** [comment]
Bisq refunds with their DAO token which is being completely removed in Haveno.

**Comment by newsyp** [comment]
hmmmm.... 
Do you know how other platforms do 2/2 multisig peer to peer trades? Are there other platforms that offer that?

**Comment by woodser** [comment]
I'm not aware of any.

**Comment by newsyp** [comment]
So let me get it straight.  

A 2/3 multisig trade involves three parties; the buyer, seller and arbitrator. The seller post a trade offer, a buyer takes the offer send his fund to the arbitrator. The arbitrator holds the funds while the seller sends his part of the trade to the buyer, once the buyer receives the funds from the seller the arbitrator releases the buyers funds to the seller; completing the trade. 

Correct me if I'm wrong or if missed something.

**Comment by erciccione** [comment]
@newsyp the arbitrator doesn't hold any fund. The 2 keys being held by taker and maker are everything needed to complete the trade. If there is a dispute, the arbitrator uses their key to decide who gets the funds.

Basically: it's a 2/3 multisig trade because only 2 keys out of 3 are needed to complete the trade. If taker and maker don't agree about the outcome of a trade, the process halts. This is where the arbitrator comes to action, using their key to confirm the trade in favour of maker or taker, providing the second key necessary to complete the trade (the other one will be provided by either maker or taker).

**Comment by erciccione** [comment]
I added an initial FAQ on github's wiki: https://github.com/haveno-dex/haveno/wiki/FAQ. We link to it from the README with #36.

This issue will be completely resolved once i've finished the doc with the trade protocol.

**Comment by erciccione** [comment]
Added the trade protocol in the FAQ. It can be expanded, but it's good for now. Closing this as resolved.
