### ISSUE TITLE
Bundle Haveno as a desktop application (proof of concept) [$500]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#255]
This issue requests creating a proof of concept to bundle Haveno as a desktop application.

The application will bundle at least Haveno's backend daemon, web front end (see [poc](https://github.com/haveno-dex/haveno-ui-poc)), monerod, and monero-wallet-rpc.

We need to investigate and determine a good approach that will work for the longterm.

Two options to consider are [Electron](https://www.electronjs.org/) and [Tauri Studio](https://github.com/tauri-apps/tauri).

The application launchers should be standalone for their respective platform, targeting Linux and MacOS initially and then eventually Windows. The preferred formats are AppImage for Linux, app "package bundle" for MacOS, and .exe for Windows.

The bundles should pull Monero binaries for monerod and monero-wallet-rpc from Haveno's custom Monero repository and verify them by hash: https://github.com/haveno-dex/monero.

The purpose of this issue is to investigate longterm approaches to eventually make an informed choice how to best package Haveno, so it should include relevant documentation and rationale. Input is welcome.

**Comment by MrCyjaneK** [comment]
Hey! I think that I'll be able to handle it.

Just a few things that I'd like to know: by bundling you mean packaging it into a single native package (.deb & friends) or approach like publishing a flatpak or appimage is preffered?
Also - should everything be built from source (I'd go for a build inside docker), or rather fetched from the releases if possible? (For example monerod and monero-wallet-rpc)

**Comment by erciccione** [comment]
hey @MrCyjaneK, we are about to add more details to this issue. The POC will need to have a comparison between Electron and Tauri, so that we can make an informed choice about which one to choose.

> by bundling you mean packaging it into a single native package (.deb & friends) or approach like publishing a flatpak or appimage is preffered?

Would be good to go with a self-contained option initially (like an appimage) and then expand, but we need to know if both options are feasible or if we would encounter issues in the future for one or the other approach (this could be an important factor for choosing between Tauri or Electron).

> should everything be built from source (I'd go for a build inside docker), or rather fetched from the releases if possible? (For example monerod and monero-wallet-rpc)

I would say we can safely included binaries if we can verify the hashes reliably, which would be the case for Monero.

**Comment by woodser** [comment]
@MrCyjaneK I updated the issue description with more detail.

> And last question: frontend is able to communicate with backend, right? There is no need for me to create a link between those two?

The frontend web app communicates with the backend Java server via a proxy (currently envoy) to translate from the browser's HTTP1 to the backend's HTTP2. All 3 will need to be running to use the application bundle.

**Comment by MrCyjaneK** [comment]
Alright. Thanks for clarification @woodser. I'll start working on a packaging.

My approach will be to create a .tar.gz with one main executable, and dependencies inside, and a Makefile that will be able to install it to the system, with that it will be easy to create AppImage, or even native packages with checkinstall.

**Comment by MrCyjaneK** [comment]
Hey the linux bundles are ready! Currently serving:
 - Pre-compiled .tar.gz - you can do `sudo make install` after extracting to install it to your system or `make install DESTDIR=/some/directory` to install it to the location that you prefer. [Download]()
 - .deb - For all the debian and ubuntu users, produced using checkinstall. [Download](https://filestore.0xff.network/file?id=kVu0E3wUS2HwuPzu)
 - .AppImage - The one everybody likes. Created using appimagetool. - [Download](https://filestore.0xff.network/file?id=Ejzx8Te1Ik5TGIwx)

After running the app it may fail to load the version, simply right click wherever you want and `reload page`. Frontend should re-check every now and then if the backend is ready, and display some loading screen.

Packaging is a bunch of shell scripts, and works almost entirely inside docker, to run build the bundles simply run `make release-linux-amd64`, it will build the docker container, extract `envoy` binary from envoy docker (`extract_static_envoy.sh`) 
and build the frontend together with backend. 
Currently embedded JDK version is downloaded at build time from AdoptOpenJDK/openjdk11-upstream-binaries, check file `download_openjdk.sh` for more.

Frontend is packaged and built using tauri.

Everything is being run by a tiny launcher app (`launcher.go`)

Link to my fork: https://github.com/MrCyjaneK/haveno

**Comment by MrCyjaneK** [comment]
And I got question about the Windows version - should it be an standalone .exe or an installer? Because afaik there is no appimage like thing on windows.
And to MacOS - I used to share .zip with all the binaries and libraries required for the app inside, will something like that do the job or is there some other preferred way on Mac?

**Comment by erciccione** [comment]
Hey @MrCyjaneK, thanks for the update. The goal of this issue is to create a PoC that will help us choose with the frontend team how to bundle the apps, not much the actual bundling. Could you share a rationale or a detailed document about why do you think the approach you are suggesting is preferred and what alternatives there are?

> And I got question about the Windows version - should it be an standalone .exe or an installer? Because afaik there is no appimage like thing on windows.

Yeah appimages don't work on Windows AFAIK. What we need from this PoC is mostly to asnwer that question, or: what's the best way to bundle Haveno? I'm not familiar with Windows, so i'm not sure of which of the 2 is preferable  :)

**Comment by MrCyjaneK** [comment]
Sure @erciccione!
Currently the app is being bundled only for linux as a: native debian package (.deb) a .tar.gz archive and an .AppImage, so people can choose whatever they prefer.
Since haveno is written in java we need a plenty of dependencies to get it running.
I'm also not a frequent windows user but usually the apps that are bigger are being distributed as a portable .zip and as a .exe installer. Which install it to either user's %AppData% directory with admin rights or to `C:\Program Files`. So I think that we should go with the M$'s way of doing things which is well accepted in the community.
And I'll need to research MacOS a bit more.

**Comment by trymeouteh** [comment]
I think these are the three best ways to ship an app on Linux.

AppImage (Works on any distro, portable, entire app is inside a single file (not a folder), easy to install, latest version available)

AUR (Work on arch distros, easy to deploy, safe and secure download, automatic updates, easy to install, latest version available)

Pacstall (Work on debian/ubuntu distros, safe and secure download, automatic updates, latest version available)

**Comment by MrCyjaneK** [comment]
Agreed on AppImage and AUR, but Pacstall is not native for debian, so why should we prefer it over apt?

**Comment by erciccione** [comment]
Hey @MrCyjaneK, now that the UI team has started working, we don't need a PoC anymore. We are closing this issue, but we would still like to reward you for the research. Please contact us on Matrix/IRC or by email and send us an xmr address :)

**Comment by MrCyjaneK** [comment]
I confirm that my address is `8AMY4isdbeD57gLkybG9Q4GkfW6PnGertFetZWr2apQmRtAmgYYHWrjG1LBXvMXuy9NUiqCebYxZQBLE4FqTNfHn1XrEp1h`

**Comment by trymeouteh** [comment]
> Agreed on AppImage and AUR, but Pacstall is not native for debian, so why should we prefer it over apt?

Pacstall does work for Debian despite what it says on their website
https://github.com/pacstall/pacstall/discussions/99
