### ISSUE TITLE
Fix Fiat <-> XMR trades

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#7]
At the moment XMR <-> Fiat trades are broken. The market appears always as xmr/xmr, even if we use fiat currencies (tested with EUR and USD).

To reproduce:

1. Alice adds her fiat account. Payment method: revolut
2. Bob adds his fiat account. Payment method: revolut
3. Both Alice and Bob have XMR on their account
4. Alice initiate a trade to sell 0.0625 XMR for USD

When looking at the "buy xmr" tab from Bob's window, Alice's offer is grey. When clicking on "TAKE OFFER TO SELL XMR", i get a pop up saying "No matching payment account" and suggest me to create one, but the payment account exists.

**Comment by j7p2** [comment]
I would like to work on this problem.
It is failing the condition test at the file desktop/src/main/java/bisq/desktop/main/offer/offerbook/OfferBookView.java at line 978.
I guess that is because PossiblePaymentAccounts.isEmpty() returns true. I didn't investigate further but I will take it from here as soon as I can.

**Comment by woodser** [comment]
Fixed with https://github.com/haveno-dex/haveno/pull/33
