### ISSUE TITLE
Sanity check for BTC addresses (altcoin account) always fails 

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#8]
When trying to add a Bitcoin address as an "altcoin" account the sanity check fails. I tried all types of Bitcoin address, but hey all fail.

**Comment by woodser** [comment]
@erciccione A regtest bitcoin address should work, like bcrt1q6j90vywv8x7eyevcnn2tn2wrlg3vsjlsvt46qz.

@premek Seems these registered accounts should validate as mainnet since payments to them are all handled externally anyway, but this would deviate from upstream and I'd consider low priority to change.

In that case, we should consider this issue expected behavior?

**Comment by erciccione** [comment]
> In that case, we should consider this issue expected behavior?

Yep. Closing.
