### ISSUE TITLE
Expand "Extra info" field on offers [0.25 XMR]

### ISSUE THREAD

**Issue by monerobull** [haveno-dex/haveno#919]
Currently the "Extra info" field on offers doesn't expand, no matter how big you pull the window. You can only scroll inside of the existing space, making it very hard to read what it says inside that field. 

An option to expand this field would be great.

What it currently looks like:
![grafik](https://github.com/haveno-dex/haveno/assets/84282654/1ecaece4-6b73-4d74-9732-3e96910a5511)

**Comment by woodser** [comment]
This is the same behavior as Bisq currently.

Adding a bounty to increase the [text area](https://github.com/haveno-dex/haveno/blob/cfd89b6da182f7e63dc1568f27d78378a2eaaf3b/desktop/src/main/java/haveno/desktop/main/overlays/windows/OfferDetailsWindow.java#L316) height only as needed for longer text, up to a maximum, and to add a scrollbar.

Otherwise we can increase the fixed height, but the bounty would not apply for this solution.

**Comment by nsec1** [comment]
I would like to try this

**Comment by woodser** [comment]
Fixed with https://github.com/haveno-dex/haveno/pull/950.

Thanks @nsec1. Please send or DM an address for payment.
