### ISSUE TITLE
Warning We did not receive a filter object from the seed nodes. This is a not expected situation. 

### ISSUE THREAD

**Issue by sacrementalguru** [haveno-dex/haveno#930]
I downloaded and installed the latest from:
https://github.com/retoaccess1/haveno-reto
and trying to follow the instructions from the error warning.

I followed the link from within the app support tab.
https://github.com/retoaccess1/haveno-reto/actions/workflows/build.yml 
because the developer has not yet enabled "issues" on https://github.com/retoaccess1/haveno-reto

**Comment by woodser** [comment]
This happens when all seed nodes are shut down at the same time. The filter can be re-added by following these instructions: https://github.com/haveno-dex/haveno/blob/master/docs/create-mainnet.md#set-a-network-filter-on-mainnet

To avoid this, more seed nodes with better uptime should be used, like on a VPS, and they should not be restarted at the same time.

Closing as it's specific to administrationn.

**Comment by fuchsto** [comment]
This issue is far from [completed](https://github.com/haveno-dex/haveno/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted), and it is below the project's standards, that it was.

In fact, software can and must support users in resolving this situation, at least by providing the information currently buried in [a comment](https://github.com/haveno-dex/haveno/issues/930#issuecomment-2118752307) on this issue.

**Comment by woodser** [comment]
This issue is expected when the network administrators do not register a filter object, or if they restart all seed nodes at the same time, causing the filter object to become unregistered.

To fix it, the network administrators should re-register the filter object.

It's not an issue with this software repository, which is working as expected, but with administration of a running network, which is beyond our scope.
